steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/low-carbon-491109/low-carbon/web-auditing:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/low-carbon-491109/low-carbon/web-auditing:${SHORT_SHA}']
options:
  logging: CLOUD_LOGGING_ONLY
